language: php

services:
  - redis-server

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - before_script: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

script:
  - ./vendor/bin/phpunit

